### ISSUE TITLE
Can you add a server to this example?

### ISSUE THREAD

**Issue by MarbilleJuntado** [invokemedia/vue-push-notification-example#2]
So that we can do something like `node app.js` and test it locally?

**Comment by james2doyle** [comment]
You can run the firebase function locally: https://github.com/invokemedia/vue-push-notification-example/blob/0aa4d86619f2233113c9decb20a53b5bc8e1bae6/firebase-function/functions/package.json#L5

There are checks in the function to allow this.

Change to firebase functions folder and run `npm run start` which will trigger the function as if it was live in firebase

**Comment by MarbilleJuntado** [comment]
Thanks. However, why am I getting this error "registration ids field cannot be empty" when I run `npm run start`?

**Comment by james2doyle** [comment]
I am guessing your database is empty and you have not added any subscribers to it

**Comment by MarbilleJuntado** [comment]
Are you referring to the Firebase realtime database? How do I add subscribers to it?
